### ISSUE TITLE
Assets are invisible.

### ISSUE THREAD

**Issue by Knaet** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#418]
**Describe the bug**
I open the build menu to place an object,but the object does not appear. The dotted white asset box appears, with a white cursor dot inside it. I can place the "object" but never see it. Dice work fine. Lights work fine. If I place a campfire, it will not be visible, but it's light is.

**To Reproduce**
1. Open build menu.
2. Select object.

**Additional context**
The game is running fine aside from that! Fast loads, good fps, music, no assets. This goes for joining other boards as well. I see light and dice and that's all.

**Comment by TheWhiteNinja91** [comment]
I had this same issue, I closed out, loaded in and the assets appeared, back to the build menu, invisible assets, steam then updated talespire, and since had no issues

**Comment by Knaet** [comment]
> I had this same issue, I closed out, loaded in and the assets appeared, back to the build menu, invisible assets, steam then updated talespire, and since had no issues

To be clear though, I've NEVER seen assets. Since initial download. Inside and outside the build menu, there is just nothing. I haven't logged into steam in a couple of days though...was yours fixed in the last couple of days?

**Comment by TheWhiteNinja91** [comment]
I think it was Friday the update was pushed if I remember right.

**Comment by TheWhiteNinja91** [comment]
But yeah

**Comment by Knaet** [comment]
Just leaving this comment as a follow up. Still having the issue.

**Comment by LuPro** [comment]
Is the issue still persisting? The new chimera update changed a lot of fundamentals about how tiles are stored and rendered - I still don't know what happened back then, but I'd say there's a fairly good chance this could be resolved now
