### ISSUE TITLE
Floor Blocks Disappearing (not high priority it is fixable with a relog)

### ISSUE THREAD

**Issue by daniel-redder** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#471]
**Describe the bug**
When Building a board some of floor blocks keep "*disappearing*" the spot in which they were placed is full no new blocks can be placed there but they are no longer visible 

**To Reproduce**
Seems to occur quite frequently to floor pieces that are above another floor piece without a wall connecting them. I do not know if this is caused by having a large map, but it is more clearly visible anyhow with a larger map.

as I mention in the title this is **NOT A HIGH PRIORITY** this bug is easily fixable with a re-log into tailspire, that said if you have time it is quite annoying especially when building multilevel structures

In a view days I'll put a quick video of it happening together.

**Comment by rich18144** [comment]
Have witnessed this myself. Not sure if it is unrelated, but at the time I was working on a multi-level building and I zoomed out to bring my view up through the second floor when it occurred. Don't believe that this was happening yesterday

**Comment by MallowOni** [comment]
My experience has been identical to Daniel's. I've been working on a tower for some time and I frequently get disappearing tiles on floors above my camera. The tiles also disappear in identical sections on floors above each other but not necessarily all the way to the top. See my attached picture for an example.

Minis can drop through the space the tiles used to occupy and if I grab any other tiles they will act as if nothing is there, meaning rather than placing a tile on top of the missing tile it will try to place the tile far below on the ground level.

**Comment by Surrwin** [comment]
I experience this bug often as well, more so on large maps.  It happens even if I started building from the lower ground level or if i'm building higher up with something underneath.  

Using the green selector to "cut away or lift away" layers, I can lift away the affected layer and then zoom back out or move the green slider back up and the affected area sometimes is fixed.

As stated in a previous comment, minis fall through these wholes.

I can easily reproduce this by making a large area with the lush grass (say 200x200) then start scrolling around the map and add a few things on top of the layer.  When you scroll back around the 200x200 area, I see wholes were tiles used to be.

![image](https://user-images.githubusercontent.com/12024708/83541516-592c3680-a4bf-11ea-98ed-408237366aea.png)

**Comment by porrages** [comment]
I'm able to repro consistently be building a map with multiple layers and then:
1. Zoom in until the upper level tiles are obscured 
2. Pan forward using W key
3. Zoom back out until the tiles pop back in
4. Pan backward using S key 

See gif and observe that the tiles in the middle go missing in a straight line https://i.imgur.com/YjUxRgE.gif

**Comment by MallowOni** [comment]
This is still happening as of the Chimera build
![image](https://user-images.githubusercontent.com/63642460/113214046-8a3fd980-923e-11eb-9020-42bc8168ef29.png)

**Comment by daniel-redder** [comment]
I have not had this happen to me since I posted this, but members of my party have had the problem.

It seems to be a local problem vs a server side one.

Should I change the name of this thread? 😅
