### ISSUE TITLE
TaleSpire, Stuck after launch.

### ISSUE THREAD

**Issue by ilderon** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#578]
So I start TaleSpire via steam. It doesn't matter how long I leave this up or how many times I restart or reinstall TaleSpire I still get stuck at this screen. Would love some help, I feel like I am missing something somewhere.

![Tale Spire](https://user-images.githubusercontent.com/67593942/86022041-bf09d080-ba21-11ea-8479-687e19380e2f.PNG)

If You need Any other information I can provide.

**Comment by MirianRoth** [comment]
I'm experiencing the same exact bug since june 29th. I've already cleared the cache, uninstalled, reinstalled, everything. I can't get over the loading screen, no matter what wi-fi I'm connected to, and all the other devices at my house load the software perfectly, logged in my steam account.

![20200702185421_1](https://user-images.githubusercontent.com/67763580/86412652-d9e47b00-bc95-11ea-8362-8a58bdde416f.jpg)

**Comment by LuPro** [comment]
There are some other reports of this kind on here already, just for completions sake: are you using some kind of VPN or are you in a non-typical set-up network (something like a university or company network with possibly restrictive firewall settings or some other network-fu that might interfere). Those things are known to sometimes mess with the connectivity. In rare cases connectivity issues could also be fixed by going from no VPN to a VPN (some other network endpoint seems to not have the issues)

**Comment by MirianRoth** [comment]
> There are some other reports of this kind on here already, just for completions sake: are you using some kind of VPN or are you in a non-typical set-up network (something like a university or company network with possibly restrictive firewall settings or some other network-fu that might interfere). It's also worth to check the windows firewall, it might have restricted talespire which can also lead to issues with connection. Those things are known to sometimes mess with the connectivity. In rare cases connectivity issues could also be fixed by going from no VPN to a VPN (some other network endpoint seems to not have the issues).

In my case, I'm not using any VPNs - it's just our home/domestic network, and all other devices connected to the same wi-fi are running TaleSpire with no problems at all. I've already checked the firewall and TaleSpire is among the list of the allowed apps. I'll try to switch to a VPN connection and see if that works.

**Comment by LuPro** [comment]
Thanks a lot for making checking, unfortunately there's not much more to do other than wait for a fix from the devs (or at least until it can be investigated to find the issue)

**Comment by MirianRoth** [comment]
> Thanks a lot for making checking, unfortunately there's not much more to do other than wait for a fix from the devs (or at least until it can be investigated to find the issue)
> 
> Edit: Maybe the log files have some more data than the dev console (I forgot whether they log in more detail or not) - you can find them in `C:\Users\AppData\LocalLow\BouncyRock Entertainment\TaleSpire\Player.log` and `Player-prev.log`, possibly those contain more information that could help diagnosing this

**Here are the contents of the Player.log file**:
Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/TaleSpire/TaleSpire_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/TaleSpire/MonoBleedingEdge/etc'
Initialize engine version: 2019.3.15f1 (59ff3e03856d)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/TaleSpire/TaleSpire_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
d3d11: QueryInterface(IDXGIFactory5) failed (80004002).
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce 820M (ID=0x1140)
    Vendor:   
    VRAM:     1974 MB
    Driver:   23.21.13.9135
Begin MonoManager ReloadAssembly
- Completed reload, in  0.707 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

New input system (experimental) initialized
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 3.856740 ms
Could not create a device for 'Telink Telink (HID)' (exception: System.Exception: State format 'SBIT' is not supported as floating-point format
  at UnityEngine.InputSystem.LowLevel.InputStateBlock.FloatToPrimitiveValue (System.Single value) [0x0014c] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.Controls.AxisControl.FinishSetup () [0x0002f] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputControl.CallFinishSetupRecursive () [0x00026] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputControl.CallFinishSetupRecursive () [0x00013] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputControl.CallFinishSetupRecursive () [0x00013] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.Layouts.InputDeviceBuilder.Setup (UnityEngine.InputSystem.Utilities.InternedString layout, UnityEngine.InputSystem.Utilities.InternedString variants, UnityEngine.InputSystem.Layouts.InputDeviceDescription deviceDescription) [0x00030] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputDevice.Build[TDevice] (System.String layoutName, System.String layoutVariants, UnityEngine.InputSystem.Layouts.InputDeviceDescription deviceDescription) [0x00053] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputManager.AddDevice (UnityEngine.InputSystem.Utilities.InternedString layout, System.Int32 deviceId, System.String deviceName, UnityEngine.InputSystem.Layouts.InputDeviceDescription deviceDescription, UnityEngine.InputSystem.InputDevice+DeviceFlags deviceFlags, UnityEngine.InputSystem.Utilities.InternedString variants) [0x0001a] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputManager.AddDevice (UnityEngine.InputSystem.Layouts.InputDeviceDescription description, System.Boolean throwIfNoLayoutFound, System.String deviceName, System.Int32 deviceId, UnityEngine.InputSystem.InputDevice+DeviceFlags deviceFlags) [0x0004e] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputManager.OnNativeDeviceDiscovered (System.Int32 deviceId, System.String deviceDescriptor) [0x000a0] in <bf5523b2240240059ae430942bd18afa>:0 ) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

-- Noice. Steamworks started fine. SteamID=76561198111825813 PersonalName=Mirian Roth BuildId=0 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Waiting for AvailableRegions. State: ConnectedToNameServer Server: NameServer PhotonNetwork.networkingPeer.AvailableRegions False 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 2878 -> priority: 1 

**And here are the contents of the Player-prev.log file**:
Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/TaleSpire/TaleSpire_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/TaleSpire/MonoBleedingEdge/etc'
Initialize engine version: 2019.3.15f1 (59ff3e03856d)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/TaleSpire/TaleSpire_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
d3d11: QueryInterface(IDXGIFactory5) failed (80004002).
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce 820M (ID=0x1140)
    Vendor:   
    VRAM:     1974 MB
    Driver:   23.21.13.9135
Begin MonoManager ReloadAssembly
- Completed reload, in  0.828 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

New input system (experimental) initialized
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 2.360053 ms
Could not create a device for 'Telink Telink (HID)' (exception: System.Exception: State format 'SBIT' is not supported as floating-point format
  at UnityEngine.InputSystem.LowLevel.InputStateBlock.FloatToPrimitiveValue (System.Single value) [0x0014c] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.Controls.AxisControl.FinishSetup () [0x0002f] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputControl.CallFinishSetupRecursive () [0x00026] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputControl.CallFinishSetupRecursive () [0x00013] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputControl.CallFinishSetupRecursive () [0x00013] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.Layouts.InputDeviceBuilder.Setup (UnityEngine.InputSystem.Utilities.InternedString layout, UnityEngine.InputSystem.Utilities.InternedString variants, UnityEngine.InputSystem.Layouts.InputDeviceDescription deviceDescription) [0x00030] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputDevice.Build[TDevice] (System.String layoutName, System.String layoutVariants, UnityEngine.InputSystem.Layouts.InputDeviceDescription deviceDescription) [0x00053] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputManager.AddDevice (UnityEngine.InputSystem.Utilities.InternedString layout, System.Int32 deviceId, System.String deviceName, UnityEngine.InputSystem.Layouts.InputDeviceDescription deviceDescription, UnityEngine.InputSystem.InputDevice+DeviceFlags deviceFlags, UnityEngine.InputSystem.Utilities.InternedString variants) [0x0001a] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputManager.AddDevice (UnityEngine.InputSystem.Layouts.InputDeviceDescription description, System.Boolean throwIfNoLayoutFound, System.String deviceName, System.Int32 deviceId, UnityEngine.InputSystem.InputDevice+DeviceFlags deviceFlags) [0x0004e] in <bf5523b2240240059ae430942bd18afa>:0 
  at UnityEngine.InputSystem.InputManager.OnNativeDeviceDiscovered (System.Int32 deviceId, System.String deviceDescriptor) [0x000a0] in <bf5523b2240240059ae430942bd18afa>:0 ) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

-- Noice. Steamworks started fine. SteamID=76561198111825813 PersonalName=Mirian Roth BuildId=0 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Waiting for AvailableRegions. State: ConnectedToNameServer Server: NameServer PhotonNetwork.networkingPeer.AvailableRegions False 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Waiting for AvailableRegions. State: ConnectedToNameServer Server: NameServer PhotonNetwork.networkingPeer.AvailableRegions False 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 47a0 -> priority: 1

**Comment by MirianRoth** [comment]
**HUGE UPDATE HERE**
 After reading the Dev Log 208 available [here](https://bouncyrock.com/news/articles/talespire-dev-log-208), I was able to change my proxy settings and **IT WORKED!!!**
 I don't know if @ilderon is still experiencing the issue, but it worked perfectly in my case. Thank you @LuPro for all the assistance!

**Comment by LuPro** [comment]
very nice to hear it works now! just wanted to go through the issues and ask you if that might be it

**Comment by ilderon** [comment]
Yep thank you @MirianRoth and @LuPro. That dev log 208 helped big time. Ive had this setting turned off for ages but it appears a windows update turned it on.
